// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package res

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed appicon-256.png
var ResAppicon256PngData []byte
var ResAppicon256Png = &fyne.StaticResource{
	StaticName:    "appicon-256.png",
	StaticContent: ResAppicon256PngData,
}

//go:embed icons/coreui/playlist-add-next.svg
var ResPlaylistAddNextSvgData []byte
var ResPlaylistAddNextSvg = &fyne.StaticResource{
	StaticName:    "icons/coreui/playlist-add-next.svg",
	StaticContent: ResPlaylistAddNextSvgData,
}

//go:embed icons/freepik/playbutton.png
var ResPlaybuttonPngData []byte
var ResPlaybuttonPng = &fyne.StaticResource{
	StaticName:    "icons/freepik/playbutton.png",
	StaticContent: ResPlaybuttonPngData,
}

//go:embed icons/majesticons/library.svg
var ResLibrarySvgData []byte
var ResLibrarySvg = &fyne.StaticResource{
	StaticName:    "icons/majesticons/library.svg",
	StaticContent: ResLibrarySvgData,
}

//go:embed icons/publicdomain/cast.svg
var ResCastSvgData []byte
var ResCastSvg = &fyne.StaticResource{
	StaticName:    "icons/publicdomain/cast.svg",
	StaticContent: ResCastSvgData,
}

//go:embed icons/publicdomain/disc.svg
var ResDiscSvgData []byte
var ResDiscSvg = &fyne.StaticResource{
	StaticName:    "icons/publicdomain/disc.svg",
	StaticContent: ResDiscSvgData,
}

//go:embed icons/publicdomain/headphones.svg
var ResHeadphonesSvgData []byte
var ResHeadphonesSvg = &fyne.StaticResource{
	StaticName:    "icons/publicdomain/headphones.svg",
	StaticContent: ResHeadphonesSvgData,
}

//go:embed icons/publicdomain/heart-filled.svg
var ResHeartFilledSvgData []byte
var ResHeartFilledSvg = &fyne.StaticResource{
	StaticName:    "icons/publicdomain/heart-filled.svg",
	StaticContent: ResHeartFilledSvgData,
}

//go:embed icons/publicdomain/heart-outline.svg
var ResHeartOutlineSvgData []byte
var ResHeartOutlineSvg = &fyne.StaticResource{
	StaticName:    "icons/publicdomain/heart-outline.svg",
	StaticContent: ResHeartOutlineSvgData,
}

//go:embed icons/publicdomain/infinity.svg
var ResInfinitySvgData []byte
var ResInfinitySvg = &fyne.StaticResource{
	StaticName:    "icons/publicdomain/infinity.svg",
	StaticContent: ResInfinitySvgData,
}

//go:embed icons/publicdomain/musicnotes.svg
var ResMusicnotesSvgData []byte
var ResMusicnotesSvg = &fyne.StaticResource{
	StaticName:    "icons/publicdomain/musicnotes.svg",
	StaticContent: ResMusicnotesSvgData,
}

//go:embed icons/publicdomain/oscilloscope.svg
var ResOscilloscopeSvgData []byte
var ResOscilloscopeSvg = &fyne.StaticResource{
	StaticName:    "icons/publicdomain/oscilloscope.svg",
	StaticContent: ResOscilloscopeSvgData,
}

//go:embed icons/publicdomain/people.svg
var ResPeopleSvgData []byte
var ResPeopleSvg = &fyne.StaticResource{
	StaticName:    "icons/publicdomain/people.svg",
	StaticContent: ResPeopleSvgData,
}

//go:embed icons/publicdomain/playlist.svg
var ResPlaylistSvgData []byte
var ResPlaylistSvg = &fyne.StaticResource{
	StaticName:    "icons/publicdomain/playlist.svg",
	StaticContent: ResPlaylistSvgData,
}

//go:embed icons/publicdomain/playqueue.svg
var ResPlayqueueSvgData []byte
var ResPlayqueueSvg = &fyne.StaticResource{
	StaticName:    "icons/publicdomain/playqueue.svg",
	StaticContent: ResPlayqueueSvgData,
}

//go:embed icons/publicdomain/sidebar.svg
var ResSidebarSvgData []byte
var ResSidebarSvg = &fyne.StaticResource{
	StaticName:    "icons/publicdomain/sidebar.svg",
	StaticContent: ResSidebarSvgData,
}

//go:embed icons/publicdomain/star-outline.svg
var ResStarOutlineSvgData []byte
var ResStarOutlineSvg = &fyne.StaticResource{
	StaticName:    "icons/publicdomain/star-outline.svg",
	StaticContent: ResStarOutlineSvgData,
}

//go:embed icons/publicdomain/star-filled.svg
var ResStarFilledSvgData []byte
var ResStarFilledSvg = &fyne.StaticResource{
	StaticName:    "icons/publicdomain/star-filled.svg",
	StaticContent: ResStarFilledSvgData,
}

//go:embed icons/publicdomain/theatermasks.svg
var ResTheatermasksSvgData []byte
var ResTheatermasksSvg = &fyne.StaticResource{
	StaticName:    "icons/publicdomain/theatermasks.svg",
	StaticContent: ResTheatermasksSvgData,
}

//go:embed icons/publicdomain/grid.svg
var ResGridSvgData []byte
var ResGridSvg = &fyne.StaticResource{
	StaticName:    "icons/publicdomain/grid.svg",
	StaticContent: ResGridSvgData,
}

//go:embed icons/publicdomain/list.svg
var ResListSvgData []byte
var ResListSvg = &fyne.StaticResource{
	StaticName:    "icons/publicdomain/list.svg",
	StaticContent: ResListSvgData,
}

//go:embed icons/publicdomain/filter.svg
var ResFilterSvgData []byte
var ResFilterSvg = &fyne.StaticResource{
	StaticName:    "icons/publicdomain/filter.svg",
	StaticContent: ResFilterSvgData,
}

//go:embed icons/publicdomain/save.svg
var ResSaveSvgData []byte
var ResSaveSvg = &fyne.StaticResource{
	StaticName:    "icons/publicdomain/save.svg",
	StaticContent: ResSaveSvgData,
}

//go:embed icons/publicdomain/saveas.svg
var ResSaveasSvgData []byte
var ResSaveasSvg = &fyne.StaticResource{
	StaticName:    "icons/publicdomain/saveas.svg",
	StaticContent: ResSaveasSvgData,
}

//go:embed icons/remix_design/broadcast.svg
var ResBroadcastSvgData []byte
var ResBroadcastSvg = &fyne.StaticResource{
	StaticName:    "icons/remix_design/broadcast.svg",
	StaticContent: ResBroadcastSvgData,
}

//go:embed icons/remix_design/repeat.svg
var ResRepeatSvgData []byte
var ResRepeatSvg = &fyne.StaticResource{
	StaticName:    "icons/remix_design/repeat.svg",
	StaticContent: ResRepeatSvgData,
}

//go:embed icons/remix_design/repeatone.svg
var ResRepeatoneSvgData []byte
var ResRepeatoneSvg = &fyne.StaticResource{
	StaticName:    "icons/remix_design/repeatone.svg",
	StaticContent: ResRepeatoneSvgData,
}

//go:embed icons/remix_design/shuffle.svg
var ResShuffleSvgData []byte
var ResShuffleSvg = &fyne.StaticResource{
	StaticName:    "icons/remix_design/shuffle.svg",
	StaticContent: ResShuffleSvgData,
}

//go:embed icons/remix_design/share.svg
var ResShareSvgData []byte
var ResShareSvg = &fyne.StaticResource{
	StaticName:    "icons/remix_design/share.svg",
	StaticContent: ResShareSvgData,
}

//go:embed icons/remix_design/updownarrow.svg
var ResUpdownarrowSvgData []byte
var ResUpdownarrowSvg = &fyne.StaticResource{
	StaticName:    "icons/remix_design/updownarrow.svg",
	StaticContent: ResUpdownarrowSvgData,
}

//go:embed themes/default.toml
var ResDefaultTomlData []byte
var ResDefaultToml = &fyne.StaticResource{
	StaticName:    "themes/default.toml",
	StaticContent: ResDefaultTomlData,
}

//go:embed LICENSE
var ResLICENSEData []byte
var ResLICENSE = &fyne.StaticResource{
	StaticName:    "LICENSE",
	StaticContent: ResLICENSEData,
}

//go:embed licenses/BSDLICENSE
var ResBSDLICENSEData []byte
var ResBSDLICENSE = &fyne.StaticResource{
	StaticName:    "licenses/BSDLICENSE",
	StaticContent: ResBSDLICENSEData,
}

//go:embed licenses/MITLICENSE
var ResMITLICENSEData []byte
var ResMITLICENSE = &fyne.StaticResource{
	StaticName:    "licenses/MITLICENSE",
	StaticContent: ResMITLICENSEData,
}
