[SupersonicTheme]
Name = "Lime Tube"
Version = "0.2"
SupportsDark = true
SupportsLight = false

[DarkColors]
PageBackground = "#030303"
PageHeader = "#030303"
ListHeader = "#111A03"
Background = "#111A03"
ScrollBar = "#AAAAAA80"
Button = "#FFFFFF1A"
DisabledButton = "#FFFFFF0A"
Disabled = "#717171"
Error = "#BFFF00"
Focus = "#BFFF00"
Foreground = "#FFFFFF"
Hover = "#FFFFFF10"
Hyperlink = "#BFFF00"
InputBackground = "#0F0F0F"
InputBorder = "#19330A"
MenuBackground = "#192605"
OverlayBackground = "#212121E6"
Placeholder = "#717171"
Pressed = "#FFFFFF20"
Primary = "#BFFF00"
Selection = "#FFFFFF1A"
Separator = "#2B2B2B"

[Sizes]
InputRadius = 8.0
ScrollBar = 6.0

[Fonts]
Normal = "Comfortaa-Regular.ttf"
Bold = "Comfortaa-Bold.ttf"
