[SupersonicTheme]
Name = "Lime Tube"
Version = "0.2"
SupportsDark = true
SupportsLight = true

[DarkColors]
PageBackground = "#030303"
PageHeader = "#030303"
ListHeader = "#111A03"
Background = "#111A03"
ScrollBar = "#AAAAAA80"
Button = "#FFFFFF1A"
DisabledButton = "#FFFFFF0A"
Disabled = "#717171"
Error = "#BFFF00"
Focus = "#BFFF00"
Foreground = "#FFFFFF"
Hover = "#FFFFFF10"
Hyperlink = "#BFFF00"
InputBackground = "#0F0F0F"
InputBorder = "#19330A"
MenuBackground = "#192605"
OverlayBackground = "#212121E6"
Placeholder = "#717171"
Pressed = "#FFFFFF20"
Primary = "#BFFF00"
Selection = "#FFFFFF1A"
Separator = "#2B2B2B"


[LightColors]
PageBackground = "#FFFFFF"
PageHeader = "#FFFFFF"
ListHeader = "#F9FFF5"
Background = "#F9FFF5"
ScrollBar = "#565656"
Button = "#0000001A"
DisabledButton = "#0000000A"
Disabled = "#888888"
Error = "#739900"
Focus = "#739900"
Foreground = "#030303"
Hover = "#00000010"
Hyperlink = "#739900"
InputBackground = "#F0F0F0"
InputBorder = "#E6FFD1"
MenuBackground = "#F2FFE8"
OverlayBackground = "#FFFFFFE6"
Placeholder = "#888888"
Pressed = "#00000020"
Primary = "#739900"
Selection = "#0000001A"
Separator = "#E0E0E0"

[Sizes]
InputRadius = 8.0
ScrollBar = 6.0

[Fonts]
Normal = "Comfortaa-Regular.ttf"
Bold = "Comfortaa-Bold.ttf"
