[SupersonicTheme]
Name = "Orange Mate"
Version = "0.2"
SupportsDark = true
SupportsLight = true

[DarkColors]
PageBackground = "#030303"
PageHeader = "#030303"
ListHeader = "#1A0C03"
Background = "#1A0C03"
ScrollBar = "#AAAAAA80"
Button = "#FFFFFF1A"
DisabledButton = "#FFFFFF0A"
Disabled = "#717171"
Error = "#FF8C00"
Focus = "#FF8C00"
Foreground = "#FFFFFF"
Hover = "#FFFFFF10"
Hyperlink = "#FF8C00"
InputBackground = "#0F0F0F"
InputBorder = "#33160A"
MenuBackground = "#261305"
OverlayBackground = "#212121E6"
Placeholder = "#717171"
Pressed = "#FFFFFF20"
Primary = "#FF8C00"
Selection = "#FFFFFF1A"
Separator = "#2B2B2B"


[LightColors]
PageBackground = "#FFFFFF"
PageHeader = "#FFFFFF"
ListHeader = "#FFF9F5"
Background = "#FFF9F5"
ScrollBar = "#565656"
Button = "#0000001A"
DisabledButton = "#0000000A"
Disabled = "#888888"
Error = "#D97600"
Focus = "#D97600"
Foreground = "#030303"
Hover = "#00000010"
Hyperlink = "#D97600"
InputBackground = "#F0F0F0"
InputBorder = "#FFE4D1"
MenuBackground = "#FFF2E8"
OverlayBackground = "#FFFFFFE6"
Placeholder = "#888888"
Pressed = "#00000020"
Primary = "#D97600"
Selection = "#0000001A"
Separator = "#E0E0E0"

[Sizes]
InputRadius = 8.0
ScrollBar = 6.0

[Fonts]
Normal = "Comfortaa-Regular.ttf"
Bold = "Comfortaa-Bold.ttf"
