[SupersonicTheme]
Name = "Purple Tube"
Version = "0.2"
SupportsDark = true
SupportsLight = true

[DarkColors]
PageBackground = "#030303"
PageHeader = "#030303"
ListHeader = "#0F031A"
Background = "#0F031A"
ScrollBar = "#AAAAAA80"
Button = "#FFFFFF1A"
DisabledButton = "#FFFFFF0A"
Disabled = "#717171"
Error = "#9D00FF"
Focus = "#9D00FF"
Foreground = "#FFFFFF"
Hover = "#FFFFFF10"
Hyperlink = "#9D00FF"
InputBackground = "#0F0F0F"
InputBorder = "#1A0A33"
MenuBackground = "#170526"
OverlayBackground = "#212121E6"
Placeholder = "#717171"
Pressed = "#FFFFFF20"
Primary = "#9D00FF"
Selection = "#FFFFFF1A"
Separator = "#2B2B2B"


[LightColors]
PageBackground = "#FFFFFF"
PageHeader = "#FFFFFF"
ListHeader = "#F8F5FF"
Background = "#F8F5FF"
ScrollBar = "#565656"
Button = "#0000001A"
DisabledButton = "#0000000A"
Disabled = "#888888"
Error = "#9D00FF"
Focus = "#9D00FF"
Foreground = "#030303"
Hover = "#00000010"
Hyperlink = "#9D00FF"
InputBackground = "#F0F0F0"
InputBorder = "#E0D1FF"
MenuBackground = "#EFE8FF"
OverlayBackground = "#FFFFFFE6"
Placeholder = "#888888"
Pressed = "#00000020"
Primary = "#9D00FF"
Selection = "#0000001A"
Separator = "#E0E0E0"

[Sizes]
InputRadius = 8.0
ScrollBar = 6.0

[Fonts]
Normal = "Comfortaa-Regular.ttf"
Bold = "Comfortaa-Bold.ttf"
