[SupersonicTheme]
Name = "Rose Pink"
Version = "0.2"
SupportsDark = true
SupportsLight = false

[DarkColors]
PageBackground = "#030303"
PageHeader = "#030303"
ListHeader = "#0F0F0F"
Background = "#0F0F0F"
ScrollBar = "#AAAAAA80"
Button = "#FFFFFF1A"
DisabledButton = "#FFFFFF0A"
Disabled = "#717171"
Error = "#FF007F"
Focus = "#FF007F"
Foreground = "#FFFFFF"
Hover = "#FFFFFF10"
Hyperlink = "#FF007F"
InputBackground = "#0F0F0F"
InputBorder = "#2B2B2B"
MenuBackground = "#212121"
OverlayBackground = "#212121E6"
Placeholder = "#717171"
Pressed = "#FFFFFF20"
Primary = "#FF007F"
Selection = "#FFFFFF1A"
Separator = "#2B2B2B"

[Sizes]
InputRadius = 8.0
ScrollBar = 6.0

[Fonts]
Normal = "Comfortaa-Regular.ttf"
Bold = "Comfortaa-Bold.ttf"
